<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class game_Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('games')->insert([
            // FPS
            ['genreID'=>'1', 'gameTitle'=>'Call of Duty', 'gameImage'=>'/assets/Call of Duty.jpg', 'gameRating'=> '17', 'gameDescription'=>'Mobile is a free-to-play shooter game developed by TiMi Studio Group and published by Activision for Android and iOS. The game was released on October 1, 2019. It saw one of the largest mobile game launches in history, generating over US$480 million with 270 million downloads within a year.', 'gamePrice'=>'200000'],
            ['genreID'=>'1', 'gameTitle'=>'Counter Strike', 'gameImage'=>'/assets/csgo.png', 'gameRating'=> '18', 'gameDescription'=>'Counter-Strike is an objective-based, multiplayer first-person shooter. Two opposing teams—the Terrorists and the Counter Terrorists—compete in game modes to complete objectives, such as securing a location to plant or defuse a bomb and rescuing or guarding hostages.', 'gamePrice'=>'350000'],
            ['genreID'=>'1', 'gameTitle'=>'Valorant', 'gameImage'=>'/assets/Valorant.jpg', 'gameRating'=> '16', 'gameDescription'=>'Valorant (stylized as VALORANT) is a free-to-play first-person hero shooter developed and published by Riot Games, for Microsoft Windows. ... The development of the game started in 2014. Valorant takes inspiration from the Counter-strike series of tactical shooters.', 'gamePrice'=>'250000'],
            ['genreID'=>'1', 'gameTitle'=>'Rainbow Six', 'gameImage'=>'/assets/Rainbow six.jpg', 'gameRating'=> '18', 'gameDescription'=>'Rainbow Six Siege is a tactical shooter with light hero elements. While games like Overwatch focus heavily on hero abilities, Siege relies more on positioning and the players ability to aim.', 'gamePrice'=>'350000'],
            ['genreID'=>'1', 'gameTitle'=>'Star Wars', 'gameImage'=>'/assets/Star wars.jpg', 'gameRating'=> '7', 'gameDescription'=>'Live your Star Wars™ dreams as you fight with your favorite dark and light side heroes across iconic locations to become master of the galaxy. Create and customize your dream squad using characters from every era, including new characters from Star Wars™: The Force Awakens, Rogue One™: A Star Wars™ Story, and Star Wars™: The Last Jedi™. Engage in epic turn-based war, confront giant bosses, progress your characters, and take your game to the next level!', 'gamePrice'=>'350000'],

            // Sandbox
            ['genreID'=>'2', 'gameTitle'=>'Minecraft', 'gameImage'=>'/assets/Minecraft.jpg', 'gameRating'=> '7', 'gameDescription'=>'Minecraft is a sandbox video game developed by the Swedish video game developer Mojang Studios. In Minecraft, players explore a blocky, procedurally generated 3D world with virtually infinite terrain, and may discover and extract raw materials, craft tools and items, and build structures or earthworks.', 'gamePrice'=>'250000'],
            ['genreID'=>'2', 'gameTitle'=>'Grand Theft Auto (GTA)', 'gameImage'=>'/assets/GTA V.jpeg', 'gameRating'=> '17', 'gameDescription'=>'Grand Theft Auto V is an action-adventure game played from either a third-person or first-person perspective. Players complete missions—linear scenarios with set objectives—to progress through the story. Outside of the missions, players may freely roam the open world.', 'gamePrice'=>'500000'],
            ['genreID'=>'2', 'gameTitle'=>'Roblox', 'gameImage'=>'/assets/roblox.png', 'gameRating'=> '10', 'gameDescription'=>'Roblox is an online game platform and game creation system developed by Roblox Corporation. It allows users to program games and play games created by other users. Roblox is free-to-play, with in-game purchases available through a virtual currency called "Robux".', 'gamePrice'=>'175000'],
            ['genreID'=>'2', 'gameTitle'=>'Citites: Skylines', 'gameImage'=>'/assets/Cities Skylines.jpg', 'gameRating'=> '13', 'gameDescription'=>'Cities: Skylines is a 2015 city-building game developed by Colossal Order and published by Paradox Interactive. The game is a single-player open-ended city-building simulation. Players engage in urban planning by controlling zoning, road placement, taxation, public services, and public transportation of an area.', 'gamePrice'=>'300000'],
            ['genreID'=>'2', 'gameTitle'=>'Red Dead Redemption', 'gameImage'=>'/assets/Red_Dead.png', 'gameRating'=> '18', 'gameDescription'=>'Red Dead Redemption is a Western-themed action-adventure game played from a third-person perspective. The player controls John Marston and completes missions—linear scenarios with set objectives—to progress through the story; in the games epilogue, the player controls John son Jack.', 'gamePrice'=>'150000'],
            
            // Battle Royale
            ['genreID'=>'3', 'gameTitle'=>'Fall Guys', 'gameImage'=>'/assets/Fall Guys.jpg', 'gameRating'=> '7', 'gameDescription'=>'Fall Guys: Ultimate Knockout flings hordes of contestants together online in a wild dash through round after round of escalating chaos until one victor remains. Battle bizarre obstacles, shove through unruly competitors, and overcome the unbending laws of physics as you stumble towards greatness.', 'gamePrice'=>'150000'],
            ['genreID'=>'3', 'gameTitle'=>'Apex Legends', 'gameImage'=>'/assets/APEX.png', 'gameRating'=> '16', 'gameDescription'=>'Apex Legends is an online multiplayer battle royale game featuring squads of three players using pre-made characters with distinctive abilities, called "Legends", similar to those of hero shooters. Each character in the squad has a unique design, personality, and abilities that provide different playstyles to the team.', 'gamePrice'=>'250000'],
            ['genreID'=>'3', 'gameTitle'=>'PUBG', 'gameImage'=>'/assets/PUBG.jpg', 'gameRating'=> '16', 'gameDescription'=>'PUBG is a player versus player shooter game in which up to one hundred players fight in a battle royale, a type of large-scale last man standing deathmatch where players fight to remain the last alive. Players can choose to enter the match solo, duo, or with a small team of up to four people.', 'gamePrice'=>'300000'],
            ['genreID'=>'3', 'gameTitle'=>'Fortnite', 'gameImage'=>'/assets/Fortnite.jpg', 'gameRating'=> '12', 'gameDescription'=>'Fortnite is a survival game where 100 players fight against each other in player versus player combat to be the last one standing. It is a fast-paced, action-packed game, not unlike The Hunger Games, where strategic thinking is a must in order to survive.', 'gamePrice'=>'200000'],
            ['genreID'=>'3', 'gameTitle'=>'Knives Out', 'gameImage'=>'/assets/Knives Out.jpg', 'gameRating'=> '13', 'gameDescription'=>'Five players in a group, a hundred players in a battle! Working with teammates to live to the end! Trust your teammates and win together with guns in hand! I am not afraid of challenges because of my trustworthy teammates!', 'gamePrice'=>'175000'],

            // MOBA
            ['genreID'=>'4', 'gameTitle'=>'DOTA', 'gameImage'=>'/assets/Dota.jpg', 'gameRating'=> '12', 'gameDescription'=>'Dota is a multiplayer online battle arena (MOBA) video game in which two teams of five players compete to collectively destroy a large structure defended by the opposing team known as the "Ancient", whilst defending their own.', 'gamePrice'=>'350000'],
            ['genreID'=>'4', 'gameTitle'=>'League of Legends', 'gameImage'=>'/assets/LOL.jpg', 'gameRating'=> '12', 'gameDescription'=>'League of Legends is a team-based strategy game where two teams of five powerful champions face off to destroy the others base. Choose from over 140 champions to make epic plays, secure kills, and take down towers as you battle your way to victory.', 'gamePrice'=>'200000'],
            ['genreID'=>'4', 'gameTitle'=>'Mobile of Legends', 'gameImage'=>'/assets/Mobile Legends.jpg', 'gameRating'=> '12', 'gameDescription'=>'Mobile Legends: Bang Bang is a multiplayer online battle arena (MOBA) game designed for mobile phones. The two opposing teams fight to reach and destroy the enemys base while defending their own base for control of a path, the three "lanes" known as "top", "middle", and "bottom", which connects the bases.', 'gamePrice'=>'200000'],
            ['genreID'=>'4', 'gameTitle'=>'Heroes of Newerth', 'gameImage'=>'/assets/Heroes of Newerth.jpg', 'gameRating'=> '18', 'gameDescription'=>'Heroes of Newerth (HoN) is a multiplayer online battle arena (MOBA) video game originally developed by S2 Games for Microsoft Windows, Mac OS X, and Linux. The game idea was derived from the Warcraft III: The Frozen Throne custom map Defense of the Ancients and was S2 Games first MOBA title.', 'gamePrice'=>'150000'],
            ['genreID'=>'4', 'gameTitle'=>'Heroes of the Storm', 'gameImage'=>'/assets/HOTS.jpg', 'gameRating'=> '18', 'gameDescription'=>'Heroes of the Storm is a MOBA game (Multiplayer Online Battle Arena). Two teams, 5 players each, fight against each other on a random battleground. The objective is to destroy the enemy base. All heroes available in the game can be purchased for virtual gold that you get for playing, leveling and daily quests.', 'gamePrice'=>'150000'],

            // Simulation
            ['genreID'=>'5', 'gameTitle'=>'The Sims', 'gameImage'=>'/assets/The Sims.jpg', 'gameRating'=> '12', 'gameDescription'=>'The Sims is a strategic life simulation video game developed by Maxis and published by Electronic Arts in 2000. It is a simulation of the daily activities of one or more virtual people ("Sims") in a suburban household near a fictional city. Players control customizable Sims as they pursue career and relationship goals.', 'gamePrice'=>'275000'],
            ['genreID'=>'5', 'gameTitle'=>'War Thunder', 'gameImage'=>'/assets/war thunder.jpg', 'gameRating'=> '12', 'gameDescription'=>'War Thunder is the most comprehensive free-to-play, cross-platform, MMO military game for Windows, Linux, Mac, PlayStation®4, PlayStation®5, Xbox One and Xbox Series X|S dedicated to aviation, armoured vehicles, and naval vessels from the early 20th century to the most advanced modern combat units.', 'gamePrice'=>'175000'],
            ['genreID'=>'5', 'gameTitle'=>'World of Warship', 'gameImage'=>'/assets/World of Warships.png', 'gameRating'=> '18', 'gameDescription'=>'World of Warships is a tactical, slow-paced shooter with three basic types of armament: ship artillery, torpedoes, and aircraft. The gameplay is team-based, and allows players to work as a team. Within a team, divisions can be established to allow a group of up to three players to join and fight battles together.', 'gamePrice'=>'250000'],
            ['genreID'=>'5', 'gameTitle'=>'Railway Empire', 'gameImage'=>'/assets/Railway Empire.jpg', 'gameRating'=> '12', 'gameDescription'=>'Railway Empire is a train and railroad company simulation that features a variety of campaigns and scenarios that initially start in 1830 and roll into the year 1910. Players create a network of train tracks and are responsible for buying and maintaining the 40 different engines available in the game.', 'gamePrice'=>'200000'],
            ['genreID'=>'5', 'gameTitle'=>'F1 2020', 'gameImage'=>'/assets/F1 2020.jpg', 'gameRating'=> '7', 'gameDescription'=>'F1 2020 allows you to create your F1 team for the very first time and race alongside the official teams and drivers. Alternatively, challenge your friends in new split-screen with casual race options for more relaxed racing. Compete on 22 circuits, with current and classic content.', 'gamePrice'=>'200000'],
        ]);
    }
}
